news/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from news import views
from.views import Home,All_news,AllCategory,Detail,Category,SignOutView,SignUpView,WeatherView,GoogleLogin,AuthRedirect,MyCategoriesView,SignInView
from rest_framework_simplejwt import views as jwt_views

urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('all-news',All_news.as_view(),name='all-news'),
    path('detail/<int:id>',Detail.as_view(),name='detail'),
    path('all-category',AllCategory.as_view(),name='all-category'),
    path('category/<int:id>',Category.as_view(),name='category'),
    path('my-categories',MyCategoriesView.as_view(),name='Fav_Category'),
    # path('signin', auth_views.LoginView.as_view(template_name='signin.html'), name='signin'),
    # path('signin', SignInView.as_view(), name='signin'),
    # path('api/signin/', SignInView.as_view(), name='signin'),
    # path('signout', auth_views.LogoutView.as_view(template_name='signout.html'), name='signout'),
    path('signup/',SignUpView.as_view(),name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', views.SignOutView.as_view(), name='signout'),
    path('weather',WeatherView.as_view(),name='weather'),
    path('google/login/?next=/', GoogleLogin.as_view(), name='google_login'),
    path('google/login/callback/', AuthRedirect.as_view(), name='google_callback'),
    path('token/',jwt_views.TokenObtainPairView.as_view(), name ='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name ='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspage/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('news.urls')),
    

]

news/models.py
from django.db import models
from .models import models
from django.contrib.auth.models import User

# Create your models here.

class ExtraField(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15,blank=True, null=True)
    addresses = models.CharField(max_length=100,blank=True,null=True)
    birthdays = models.CharField(max_length=50,blank=True,null=True)
    def __str__(self):
         return self.user.username

class Categories(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')
    class Meta:
        verbose_name_plural='categories'
    def __str__ (self):
        return self.title   

class News(models.Model):
    category=models.ForeignKey(Categories,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    class Meta: 
        verbose_name_plural='news'
    def __str__(self):
        return self.title
    
class UsersFavoriteCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.user)

news/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

news/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import News, Categories,UsersFavoriteCategory,ExtraField
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserRegistrationForm
from django.http import HttpResponse,JsonResponse
from google_auth_oauthlib.flow import Flow
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from rest_framework.authentication import SessionAuthentication
from django.views import View
from django.views.generic import ListView
from.serializers import NewsSerializer,UserSerializer,CategoriesSerializer
from dateutil import parser
import requests,os
from django.views.decorators.csrf import csrf_exempt
from google.oauth2 import id_token
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.decorators import api_view
from rest_framework_jwt.settings import api_settings
from rest_framework_simplejwt.authentication import JWTAuthentication


# Home Page
class Home(APIView):
    def get(self, request, *args, **kwargs):
        first_news = News.objects.first()
        three_news = News.objects.all()[1:3]
        three_categories = Categories.objects.all()[0:3]
        data = {
            'first_news': NewsSerializer(first_news).data,
            'three_news': NewsSerializer(three_news, many=True).data,
            'three_categories': []
        }
        for category in three_categories:
            news = News.objects.filter(category=category)[:3]
            category_data = {
                'id': category.id,
                'title': category.title,
                'news': NewsSerializer(news, many=True).data
            }
            data['three_categories'].append(category_data)  
        return Response(data, status=status.HTTP_200_OK)


# Fetch and display the list of all_news
class All_news(APIView):
    def get(self, request):
        all_news = News.objects.all()
        serializer = NewsSerializer(all_news, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)    


# Fetch the detailed full news    
class Detail(APIView):
    def get(self, request, id):
        news = get_object_or_404(News, id=id)
        serializer = NewsSerializer(news)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
# Fetch all category 
class AllCategory(APIView):
    def get(self, request):
        cats = Categories.objects.all()
        serializer = CategoriesSerializer(cats, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

# Fetch all news from selected category
class Category(APIView):
    def get(self, request, id):
        category = get_object_or_404(Categories, id=id)
        news = News.objects.filter(category=category)
        serializer = NewsSerializer(news, many=True)
        return Response({
            'all_news': serializer.data,
            'categories': CategoriesSerializer(category).data
        }, status=status.HTTP_200_OK) 
    
# To signup the user        
class SignUpView(APIView):
    def get(self, request):
        form = UserRegistrationForm()
        context = {'form': form}
        # return render(request, 'signup.html', context)
        return JsonResponse(context)
    def post(self, request):
        form = UserRegistrationForm(data=request.data)
        if form.is_valid():
            form.save()
            # return JsonResponse({'success': True},status=status.HTTP_201_CREATED)
            return redirect('http://127.0.0.1:3000/signin')
        else:
            errors = dict(form.errors.items())
            return JsonResponse({'success': False, 'errors': errors}, status=status.HTTP_400_BAD_REQUEST)
                
#To Signin the user for login    
class SignInView(APIView):
    def get(self, request):
        form = AuthenticationForm()
        context = {'signin_form': form} 
        return render(request, 'signin.html', context)
    @csrf_exempt
    def post(self, request):
        form = AuthenticationForm(request, data=request.data)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                refresh = RefreshToken.for_user(user)
                token = str(refresh.access_token)
                print("Generated token:", token)
                return Response({'success': True,'token': token})
            else:
                form.add_error(None, "Invalid username or password.")
        errors = dict(form.errors.items())
        return Response({'success': False, 'errors': errors}, status= status.HTTP_400_BAD_REQUEST)
          
# To Signout the  user   
class SignOutView(APIView):
    permission_classes = (IsAuthenticated,)
    def get(self, request):
        logout(request)
        return Response(status=status.HTTP_200_OK)  
    @csrf_exempt  
    def post(self, request):     
          try:
               refresh_token = request.data["refresh_token"]
               token = RefreshToken(refresh_token)
               token.blacklist()
               return Response(status=status.HTTP_205_RESET_CONTENT)
          except Exception as e:
               return Response(status=status.HTTP_400_BAD_REQUEST)


# Weather Report
class WeatherView(APIView):
    def get(self, request):
        api_key = os.getenv('API_KEY')
        city = "Madurai"
        api_url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}"
        response = requests.get(api_url)
        weather_data = response.json()
        return Response(weather_data, status=200)

# To Authenticate the user with Google account
class GoogleLogin(View):
    def get(self, request):
        client_id = os.getenv('CLIENT_ID')
        redirect_uri = 'http://127.0.0.1:8000/google/login/callback/'
        scope = ['https://www.googleapis.com/auth/userinfo.email', 
                 'https://www.googleapis.com/auth/userinfo.profile',
                 'https://www.googleapis.com/auth/user.phonenumbers.read',
                 'https://www.googleapis.com/auth/user.addresses.read',
                 'https://www.googleapis.com/auth/user.birthday.read',
                 ]
        auth_url = 'https://accounts.google.com/o/oauth2/v2/auth?' + \
            f'client_id={client_id}&' + \
            f'redirect_uri={redirect_uri}&' + \
            f'scope={" ".join(scope)}&' + \
            f'response_type=code'
        return redirect(auth_url)    
    
# To redirect the URL after getting the auth_code from API  
class AuthRedirect(View):
    def get(self, request):
        token_url = 'https://oauth2.googleapis.com/token'
        client_id = os.getenv('CLIENT_ID')
        client_secret = os.getenv('CLIENT_SECRET')
        redirect_uri = 'http://127.0.0.1:8000/google/login/callback/'
        code = request.GET.get("code")
        params = {
            "code": code,
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uri": redirect_uri,
            "grant_type": "authorization_code",
        }
        response = requests.post(token_url, data=params)
        token_data = response.json()
        access_token = token_data.get('access_token')
        if access_token:
            profile_url = 'https://www.googleapis.com/oauth2/v2/userinfo'
            people_url = 'https://people.googleapis.com/v1/people/me?personFields=phoneNumbers,addresses,birthdays'
            headers = {'Authorization': f'Bearer {access_token}'}
            profile_response = requests.get(profile_url, headers=headers)
            people_response = requests.get(people_url, headers=headers)
            profile_data = profile_response.json()
            email = profile_data.get('email')
            name = profile_data.get('name')
            people_data = people_response.json()
            phone_number = None
            if 'phoneNumbers' in people_data:
                phone_number = people_data['phoneNumbers'][0]['value']
            addresses = None    
            if 'addresses' in people_data:
                addresses = people_data['addresses'][0]['formattedValue']
            birthdays = None    
            if 'birthdays' in people_data:
                birthdays = people_data['birthdays'][0]['date']   
            if email:
                first_name = name.split()[0]
                try:
                    user = User.objects.get(email=email)
                    user.first_name = first_name
                    user.save()
                    extra_field = ExtraField.objects.get(user=user)
                    extra_field.phone_number = phone_number
                    extra_field.addresses = addresses
                    extra_field.birthdays = birthdays
                    extra_field.save()
                except User.DoesNotExist:
                    user = User.objects.create_user(first_name, email=email, first_name=first_name)
                    extra_field = ExtraField.objects.create(user=user,phone_number=phone_number,addresses=addresses, birthdays=birthdays)
                login(request, user)
                return redirect('http://127.0.0.1:3000/')
        return redirect('http://127.0.0.1:3000/signin')
    

# To view the User's Favourite Category
class MyCategoriesView(ListAPIView):
    serializer_class = NewsSerializer
    permission_classes = [IsAuthenticated]

news/templates/Fav_Categories.html
{% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">List of My Favourite News:</h3>	
    <!-- News Box -->
    {% for news in fav_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img 	src="/media/{{news.image}}" class="card-img-top" >
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-success">Read Full</a></p>			
	      </div>
	    </div>
	  </div>
    </div>	
    {% endfor %}
</main>
{% endblock %}

news/templates/all-news.html
<!-- {% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All News</h3>
    News Box
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="media/{{news.image}}" class="card-img-top" >
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-success">Full News</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %} -->

news/templates/category-news.html
{% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">List of {{categories.title}} News</h3>	
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img 	src="/media/{{news.image}}" class="card-img-top" >
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-success">Read Full</a></p>			
	      </div>
	    </div>
	  </div>
    </div>	
    {% endfor %}
	<p  class="card-text"><a href="/all-category" class="btn btn-sm btn-success">Previous Page</a></p> 
</main>
{% endblock %}

news/templates/category.html
{% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All Categories</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" >
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-success">All News</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

news/templates/detail.html
{% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" >
			  <div class="card-body">
			    <p class="card-title h1">{{news.title}}</p>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
				<!-- <p class="card-text"><a href="/category/{{cat.id}}" class="btn btn-sm btn-success">Previous Page</a></p> -->				
			  </div>
			</div>		
			<p class="card-text"><a href="/all-news" class="btn btn-sm btn-success">Previous Page</a></p>
	</div>	
</main>
{% endblock %}

news/templates/home.html
{% extends 'main.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" >
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-success">Full News</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" >
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-success">Full News</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} </h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="media/{{news.image}}" class="card-img-top" >
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-success">Full News</a></p>
				</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% endfor %}
</main>
{% endblock %}

news/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
	<!-- Top News -->
	<nav class="navbar navbar-exapand-lg navbar-dark bg-dark">
		<div class="container row d-flex p-2 justify-content-around">
			<div><a class="navbar-brand " style="width: 9rem" href="/">M_K News</a></div>
			<div style="width:18"><a class="text-decoration-none" href="admin/">Admin</a></div>
			<div style="width:18"><a class="text-decoration-none" href="/">Home</a></div>
			<div style="width:18"><a class="text-decoration-none" href="{% url 'all-news' %}">All News</a></div>
			<div style="width:18"><a class="text-decoration-none" href="{% url 'all-category' %}">All Categories</a>
			</div>
			<div style="width:18"><a class="text-decoration-none" href="{% url 'weather' %}">Weather </a></div>
			<!-- <div style="width:18"><a class="text-decoration-none" href="{% url 'Fav_Category' %}">MyCategories </a></div>		   -->
		</div>
		</div>
		<div class="d-flex p-2 justify-content-end">
			{% if user.is_authenticated %}
			<div class="row">
				<div>
					<!-- <div style="width:18"><a class="text-decoration-none" href="{% url 'Fav_Category' %}">My Favourites </a></div>	 -->
				</div>
				<div class="col-lg-0" style="width:18"><a class="text-decoration-none"
						href="{% url 'Fav_Category' %}">My Favourites </a></div>
				<div>
					<a class="fs-1 text-end font-monospace fw-bold text-white">Welcome {{user.username}}</a>
				</div>
				<div class="col-lg-6" style="width:18"><a class="text-decoration-none"
						href="{% url 'signout' %}">SingOut </a></div>
			</div>
			{% else %}
			<div class="col-lg-12 " style="width:18"><a class="text-decoration-none" href="{% url 'signin' %}">SignIn
				</a></div>
			{% endif %}
		</div>
	</nav>
	{% block content %}
	{% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
		integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
		crossorigin="anonymous"></script>
</body>	
</html>

news/templates/signin.html
<!DOCTYPE html>
<html>
<head>
  <title>SignIn</title>
</head>
{% load socialaccount %}
<body>
  <h1>Welcome to SignIn Page</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
    {% endfor %}
    <button type="submit">SignIn</button>
    <p>Don't have an account? <a href="{% url 'signup' %}">Signup here</a></p>
    <p>or</p>
    <button class="btn btn-outline-info">
      <a href="{% url 'google_login' %}">
          <i class="fab fa-google"></i>
          SignIn with Google
      </a>
    </button>
</form>
</body>
</html>

news/templates/signout.html
{% extends "main.html" %}

{% block content %}
  <h2>You have been logged out.</h2>
  <a href="{% url 'signin' %}"> SignIn for Existing User</a>
  <p><a href="{% url 'signup' %}"> Register for New User </a></p>
{% endblock %}

news/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Register Page</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
    
        {% for field in form %}
            <div>
                <p>{{ field.label }}: <br> {{ field }}</p> 
            </div>
        {% endfor %}
        <button type="submit">Register</button>
    </form>
<br>
{{ Message }}
</body>
</html> 

news/templates/weather.html
{% extends "main.html" %}

{% block content %}
<body>
    <main class="container mt-3 mb-5">
        <h3 class="border-bottom pb-1 my-4">Weather Report</h3>
      
        <!-- <h1>The weather report for the country of {{weather_data.sys.country}}</h1> -->
        <p>Temperature: {{ weather_data.main.temp }}°C</p>
        <p>Humidity: {{ weather_data.main.humidity }}%</p>
        <p>Wind Speed: {{ weather_data.wind.speed }}m/s</p>
</body>
{% endblock %}
</html> 